[package]
name = "evm-coprocessor"
version = "0.0.1"
edition = "2021"

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-timers = "0.9.0"
serde = "1.0.204"
serde_bytes = "0.11.15"
thiserror = "1.0.63"

[build-dependencies]
dotenv = "0.15.0"
ic-cdk-bindgen = "0.1.3"
